services:
  app:
    ports:
      - "8787:8787"

  db:
    ports:
      - "5532:5432"

  db-e2e:
    ports:
      - "5433:5432"

  db-e2e-fixtures:
    ports:
      - "5434:5432"

  db-e2e-harness:
    ports:
      - "5435:5432"

  db-e2e-local:
    ports:
      - "5436:5432"
